name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  flake:
    name: Flake checks

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v9

      - name: Run checks
        run: |
          nix flake check --print-build-logs --show-trace
